### ISSUE TITLE
(mac osx 10.7.5) cannot playback video on webpage

### ISSUE THREAD

**Issue by mrkapqa** [wicknix/Arctic-Fox#111]
Hello,

iam using Mac OS X 10.7.5 and would like to find a way to playback this video here

https://home.solari.com/coming-thursday-solari-wellness-series-best-ways-to-strengthen-your-immune-system-an-interview-with-dr-thomas-levy/

desired playback>
( A PREVIEW)

it would hover over the video, but not play it.

is there something i can do about it?

tried several browser,
firefox legacy, arctic fox, seamonkey 2.46, safari 5 (yes),
none would allow for playback.

thanks.
richard

**Comment by wicknix** [comment]
Give chromium-legacy a try. It's current chromium back ported to 10.7-10.10.
https://github.com/blueboxd/chromium-legacy

**Comment by mrkapqa** [comment]
thanks very much, got so much info about it, that nearly forget about them.
now it would function, with the latest /stable build.
https://github.com/blueboxd/chromium-legacy/releases/tag/stable
