### ISSUE TITLE
Endianness for certain web sites

### ISSUE THREAD

**Issue by gianlucarenzi** [wicknix/Arctic-Fox#15]
How can I have an attachment? Because I have a screenshot for an issue for graphics. Drag and drop does not work (I am using MATE Ubuntu 16.04 LTS) and pasting it simply add the file path...
 Try to go to:
https://www.powerpc-notebook.org/en/
and you will see the issue

**Comment by wicknix** [comment]
This is an issue with the bundled webp on ppc. This doesn't happen on x86. A simple solution is go in to about:config and change image.http.accept 
Default is: image/webp,image/jxr,image/png,image/*;q=0.8,*/*;q=0.5
Change to: image/jxr,image/png,image/*;q=0.8,*/*;q=0.5
Reload that website. The images should look correct now.

**Comment by rmottola** [comment]
It would be good to check this and see if can be fixed. What is interesting is that I did not disable it yet
https://html5test.com/

reports WebP not supported but we accept and show WebP images (albeit broken on PPC... but working on x86)

**Comment by rmottola** [comment]
I updated in my branch libwebp to 0.6 series, since it should have some bigendian fixes - but it does not improve things, unfortunately.

**Comment by rmottola** [comment]
I updated to even latest libwebp as in FireFox, but it did not improve anything. We will have now more optimized code for intel and ARM, but no fixes for PPC :( The code should have many Endianess fixes, but no help for us.

**Comment by classilla** [comment]
It's not `libwebp` that's the problem now, it's your high-level decoder. WEBP works fine in TenFourFox; see https://github.com/classilla/tenfourfox/issues/501 . You're welcome to use that.

**Comment by wicknix** [comment]
Thanks! We will definitely check into that.

**Comment by rmottola** [comment]
I have been looking into this the past days already, I am checking out InitInternal() of nsWEPPDecoder AF and TFF has significantly different code.

Especially, TFF has now:
#ifdef __ppc__
  mDecBuf.colorspace = MODE_Argb;
#else
  mDecBuf.colorspace = MODE_bgrA;
#endif

so standard for intel is bgrA, instead in AF it is rgbA (and works on intel). I tried on PPC both Argb and bgrA with the only effect of making other funny colors. There would be a 4th option MODE_rgbA_4444 which I don't know what it is. Do you?
I will blindly experiment with non pre-multiplied Alphas, but it makes no sense, so I suppose there is another issue elsewhere.

**Comment by classilla** [comment]
If that's the case, this may relate to changes in https://bugzilla.mozilla.org/show_bug.cgi?id=986328 which aren't on 38ESR (which is effectively your platform base).

**Comment by rmottola** [comment]
WebP display was fixed and is in .18 release.
Does it fix the original issue?
The only other specific bug I was able to isolate on endianness and images are filters, mentioned in [https://github.com/wicknix/Arctic-Fox/issues/34](url)

**Comment by wicknix** [comment]
I haven't run in to any more endianness issues. I'll consider this fixed and close it.
