### ISSUE TITLE
AltiVec Blur code from TFF

### ISSUE THREAD

**Issue by rmottola** [wicknix/Arctic-Fox#18]
Check if we can import the altivec blurring code of

https://github.com/classilla/tenfourfox/issues/189

(and check if there are updates to that - TenFourFox lost history of repository, so difficult to check)

**Comment by wicknix** [comment]
I've downloaded the patch. I'll dissect it and see if we can use it, or parts of it at least. Might help the ppc linux builds.

**Comment by rmottola** [comment]
@wicknix fine! I just added it up to the things TODO, nothing critical.
If, while applying the patch, you notice some prerequisites, different or missing method signatures, please do not work around it, but let me know, so that we check any missing patches to bring up ArcticFox to TFF levels.
