### ISSUE TITLE
Parts of the UI become unresponsive after a time (PM 28.3).

### ISSUE THREAD

**Issue by Peacock365** [wicknix/Arctic-Fox#23]
Hi wicknix,

there is a bug in the UI of your unofficial Pale Moon 28.3 build. After some time, UI elements become unresponsive. One example is the search provider drop-down menu in the search bar. I haven't found a reason for this behavior yet.

Pale Moon 28.3, macOS 10.14.3 Mojave.

Cheers

PS: I know that this is the Arctic Fox issue tracker, but since I don't see any point to sign up for the Pale Moon forum to report a single bug I thought I might as well post it here.

**Comment by wicknix** [comment]
Please post to the correct issue tracker. Thanks. 
https://github.com/MoonchildProductions/UXP/issues/689
