### ISSUE TITLE
Missing Certificate Authorities?

### ISSUE THREAD

**Issue by countvajhula** [wicknix/Arctic-Fox#39]
Hi there, thank you for making this great browser! Snow Leopard 4 lyf 😜 Just reporting that the certificate issuer was not recognized on [this site](https://www.edd.ca.gov/) ("Issued by: COMODO RSA Organization Validation Secure Server CA"). Chrome did recognize it on a modern laptop. Since Chrome considered it trusted, I verified that the issuer and SHA256 signatures were the same and then added the security exception. Just reporting it in case it represents that a database of trusted certificate authorities is missing or needs to be updated.

**Comment by wicknix** [comment]
Thanks. I probably haven't updated the certs since 27.9.15 and they were from FF60. I'll have them updated by the time we release 27.9.19.
