### ISSUE TITLE
i guess no more updateds to that repositories?

### ISSUE THREAD

**Issue by Sa-Ja-Di** [wicknix/Arctic-Fox#40]
As you have decided to stop contributing in the Pale Moon forums, i guess that means also no further updating for that repositories here?

Thanks for a possible answer in advance!

**Comment by wicknix** [comment]
No, sorry. They pi$$ed me off over there, so i quit. Apparently volunteering your free time and not getting things done "NOW! TODAY!" is frowned upon over there. So screw 'em. I've decided since then to fork and rebrand their UXP based browsers for PowerPC Linux instead. ;)
