### ISSUE TITLE
System Theme not theming Arctic Fox.

### ISSUE THREAD

**Issue by RetroSoftwareRepository** [wicknix/Arctic-Fox#47]
My PowerMac G5 running Fienix Lite after updating to build 27.9.18 still has no theme applied by the system for some reason. Also the About screen shows a glitched logo

file:///home/alex/ArcicFox_2019-December-10.png

**Comment by wicknix** [comment]
That's an issue with fienix's .deb package. The arcticfox.desktop file symlinks to the binary rather than use its actual path. If you manually launch it, it themes fine. Example: cd /usr/lib/arcticfox then ./arcticfox will have gtk themed appearance. Edit the .desktop file to fix this.
