### ISSUE TITLE
PPC64 Little Endian Support?

### ISSUE THREAD

**Issue by djames1** [wicknix/Arctic-Fox#58]
I was looking into this project and saw no mention of support for IBM POWER little endian CPUs. I was wondering if you support that, as in you would accept bug fixes if someone is running this on PPC64LE? I was able to compile it successfully on my POWER9 Little Endian system using GCC 6.5 and it seems to work fine other than the obvious lack of JIT. It's much faster than Firefox or UXP based browsers on my machine.

The same question can be asked for UXP4PPC32, but that does not successfully compile on my machine.

Thanks!

**Comment by wicknix** [comment]
I stripped all the hard coded 64-bit code from UXP4PPC32 which is more than likely why it failed for you. You could probably add -m64 to your compiler flags however, and it should work. Make sure to grab the release version, as my master branch on github is currently busted. I don't own any ibm power hardware (yet), just old ppc macs, so I have no way to test beyond those and some legacy x86 hardware.

As for Arctic Fox, sure, if you have bug fixes that don't destroy the ability to build on OSX, win32 or ppc32/64 linux/bsd we would certainly review them and add them. We would like to be as portable and cross platform as possible.

**Comment by djames1** [comment]
@wicknix Awesome, thanks! I will submit patches if I find any bugs moving forward. I will open an issue on the UXP4PPC32 repo if I am not able to get it building.
