### ISSUE TITLE
Browser for Debian 7 /powerpc64

### ISSUE THREAD

**Issue by mrkapqa** [wicknix/Arctic-Fox#63]
Hello ,

i am writing here to know if there is a release that runs on a Powermac G5 that has Debian 7 Powerpc64 installed instead of Powerpc.
It seems the release linked on point 2 of the Frontpage is only for Powerpc (Release 27.10.1-linux-powerpc.deb) °it would install on Powerpc64, but not start on Debian 7 as it seems.

Please advise.

**Comment by wicknix** [comment]
Currently only Debian 8 and above is supported on 32bit, and Debian 10/Sid on 64bit when it comes to Debian PPC. It may build for Debian 7 ppc64, but none of us have 7 installed to build or test with. The oldest i have is ubuntu12 32bit. Riccardo uses 10/Sid 32bit and Christian (Xeno74) contributes the 64bit builds for Fedora/OpenSuse and Debian 10/Sid.

Your options would be, try to compile it on your machine, or install one of the many supported flavors of Linux it's known to run on. 32 bit Fienix, Void 32bit (glibc version), 32 bit Debian 8-Sid, 32bit Ubuntu 12-16 (xeno74 built a version for 32 bit ubuntu 10 as well) or 64 bit Debian 10/Sid. FYI the 32bit Ubuntu's and Fienix will work on a G5 with a 64bit kernel but use a 32bit rootfs.

**Comment by mrkapqa** [comment]
Thanks,
i use(d)  Debian 7 on several computer, 
and with i386 or amd64 probably i could run quite the latest Firefox ESR;
therefore my thought is it should be "easily" possible to build a newer Firefox like FF45 or FF52, but please correct me if am wrong.
Tried with Firefox Mozilla site for building instructions, but could not sail out with them.

**Comment by wicknix** [comment]
You can use this guide as a starting point: https://developer.palemoon.org/build/linux/
You'll need gcc-4.8 (4.7 *might* work) or higher. Then use the premade 64bit mozconfig supplied in AF's source tree. Also, if you dont have 2-4gb of ram you'll need to use 2gb of swap or a swapfile or the build will fail during the linking stage.
