### ISSUE TITLE
SSL errors accessing thing like GitHub.

### ISSUE THREAD

**Issue by linkslice** [wicknix/Arctic-Fox#69]
Many sites have recently starting giving SSL errors.

**Comment by wicknix** [comment]
What OS? Do you have any examples? I know github functionality is partially broken, but i have yet to run in to any SSL issues on github or any other site for that matter.

**Comment by linkslice** [comment]
Weird. I can't replicate it anymore. I got SSL on just about every site and now they all work. /shrug
