### ISSUE TITLE
literally nothing works on here

### ISSUE THREAD

**Issue by ShadowMan44** [wicknix/Arctic-Fox#72]
YouTube? Doesn't play videos
Discord? Won't get past the startup screen
Ok, it's a bit exaggerated. "most" basic websites like Twitter and Reddit work favorably but these are going to need some working on if you want your browser to get popular.

**Comment by wicknix** [comment]
YouTube works just fine:
[![yt-works-fine.png](https://i.postimg.cc/gJnh6NkV/yt-works-fine.png)](https://postimg.cc/G8ntWPDt)

Discord requires more than AF can offer. The code AF is based on is old by todays standards. It's really just a niche browser for older devices that receives bug fixes similar to what TenFourFox does for old PowerPC Macs.

**Comment by rmottola** [comment]
Youtube continues to work both in mobile as in desktop mode, as of current git.
