### ISSUE TITLE
Possible to update codebase?

### ISSUE THREAD

**Issue by jkrosado** [wicknix/Arctic-Fox#77]
Every "modern" Snow Leopard browser I have tried is stuck with the Firefox 52.9 codebase. None of these browsers can run Discord properly thanks to this, either a black screen or just freezing randomly while running. FF69 can run it properly on Lion, but my Lion install no longer boots (my fault) so I'm stuck with 10.6. Can this be updated to at least Firefox 56?

**Comment by wicknix** [comment]
No.

If all you want is a usable discord experience you have a few options yet on 10.6.

1) SpiderWeb browser. Discord redraws slowly, but it works. I've used it by using a firefox 78 useragent override. https://forums.macrumors.com/attachments/discord-snowleopard-png.1808167/

2) Bitlbee with discord plugin. Which i have available here: https://macintoshgarden.org/apps/bitlbee-irc-im-gateway-discord-plugin (it works fine via rosetta)

3) Install Linux in virtualbox and use current chrome or firefox. I created a small live disk specifically to use in snow leopard when it comes to stubborn websites. See here: https://forums.macrumors.com/threads/linux-recovery-cd-or-virtual-machine-for-old-macs.2283084/
