### ISSUE TITLE
Password to extract 7z for WinXP ?

### ISSUE THREAD

**Issue by lambic12** [wicknix/Arctic-Fox#84]
Hello, I downloaded arcticfox-27.11.0.win32-git-20201121.7z.
Extract is asking for a password.
Please can you provide it ?

**Comment by wicknix** [comment]
There is no password on the archive. Maybe try another utility like 7zip.

**Comment by JeanPaulLucien** [comment]
@lambic12 this is your extractor issue.

**Comment by JeanPaulLucien** [comment]
@wicknix not confirm.

**Comment by wicknix** [comment]
Well, there is no password. Try an **updated** archive utility. Extracts fine on my XP machine with 7zip.
