### ISSUE TITLE
Google accounts and netflix not working

### ISSUE THREAD

**Issue by person246** [wicknix/Arctic-Fox#91]
First of all, when I click on a show on netflix and play it, it just shows a black screen. Safari 5 can play netflix so why not Arctic Fox? Secondly, when I attempt to sign in to my google account, after I click on the next button after entering my email address, it'll just show half of my email address. Again, Safari 5 can sign in. Except for these problems, Arctic Fox is a dream to use and is my favourite browser for Mac OS X Snow Leopard. Keep up the good work! Hopefully in a later version you'll fix these problems.

**Comment by wicknix** [comment]
Mozilla based browsers require googles widevine plugin to play DRM content like netflix. Your old safari 5 is probably still using microsofts silverlight plugin, which i thought netflix dropped support for years ago. At any rate, netflix will never work with arctic fox thanks to google. The rest of googles services will be hit or miss as well. They may work, they may not. Try using a mobile user agent on google sites. That generally works most of the time.

**Comment by person246** [comment]
Thanks for the help @wicknix!
