### ISSUE TITLE
additional search engines cannot be added, yielding "Download Error" instead

### ISSUE THREAD

**Issue by IvanExpert** [wicknix/Arctic-Fox#92]
In Arctic Fox 39.0, attempting to add a search engine from the Pale Moon search plugins page yields a "Download Error", and the search engine is not added. This is a problem if you want to have Google search integrated into a new installation of Arctic Fox.

I regressed this against Pale Moon 27.9.4 and it has the identical issue, so I imagine that's where the problem lies. Search engines can be added normally with the latest version of Pale Moon (29.4.4).

Thank you for continuing to develop and provide Arctic Fox!

**Comment by wicknix** [comment]
This isn't an Arctic Fox issue. The Pale Moon team have made it impossible to install their add-ons and extensions on any browser but Pale Moon. To use google or bing from within duckduckgo just use the built in feature. Type: !g <search phrase> for google results, or !b <search phrase> for bing results.

**Comment by IvanExpert** [comment]
Got it. That's a bummer. Thanks for the workaround.
