### ISSUE TITLE
Build on Windows with GCC?

### ISSUE THREAD

**Issue by 3oheicrw** [wicknix/Arctic-Fox#95]
I don't want to use MSVC. GCC now also has UCRT64 support apart from traditional MSVCRT. Could you make it possible to build on Windows using GCC?

The GCC I got is from there: https://winlibs.com/

**Comment by roytam1** [comment]
> I don't want to use MSVC. GCC now also has UCRT64 support apart from traditional MSVCRT. Could you make it possible to build on Windows using GCC?

no idea here, since I only use MSVC to build. you may have a look on older version of tor browser to see if there is any additional patch you have to apply in order to build with mingw-gcc.

**Comment by 3oheicrw** [comment]
Currently will not work with GCC. I think we should just give up on this.

**Comment by 3oheicrw** [comment]
https://github.com/rmottola/Arctic-Fox/issues/89
